@startuml
title "Budget Management: Reset password"
footer "Copyright (c) 2023 - Fathalfath30 All Right Reserved | https://github.com/fathalfath30"

autonumber
!theme plain
skinparam minClassWidth 100
skinparam handwritten false

actor "**USER**" as user
box Budget Management #dbf1f3
  participant "**Frontend**\n**service**" as fe order 1
  participant "**Backend**\n**service**" as be order 2
  participant "**Database**" as db order 3
end box

box 3rd Party #dbe3f3
  participant "**Google**\n**Recaptcha**" as google_r order 4
  participant "**Mail**\n**Service**" as email order 5
end box

user -> fe: click link from email
fe -> be: request validate token
alt total request > 3 in 1 minutes
  be --> fe: status code: **429 (to many request)**
  note over fe
    **error message:**
    You've sent to many request to us recently,
    please try again later
  end note
  fe --> user: display error message
else "else -> goto next step"
end alt
@enduml
